version: '3.8' # Version of compose

services: # One containerized piece
  api:
    build:
      context: . # Docker file and code in same container
      dockerfile: Dockerfile # Use this dockerfile to build img
    image: movie-ticket-booking-api
    container_name: movie-ticket-booking-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes: # Share files between computer and container no rebuild
      - ./:/usr/src/app
      - /usr/src/app/node_modules # dont mount node_module
    networks:
      - app-network

networks:
  app-network: # Custom network
    driver: bridge # Default network