version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: movie-ticket-booking-api
    container_name: movie-ticket-booking-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge